name: HW03 Unittesting
on:
  push:
    branches:
      - hw03-main
      - mainpy_branch
      - template_branch


jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.11.5"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install flask
        run: |
          pip install flask
      - name: Install pytest
        run: |
          pip install pytest
      - name: Install requests
        run: |
          pip install requests
      - name: Run tests
        run: pytest
