# This yaml only pushes the code to the existing lambda. You must create
#  the lambda function(s) in the AWS Console first, before triggering the pipeline. 
# Source:  https://www.whitespectre.com/ideas/multiple-aws-lambda-deployment-with-github-actions/
on:
  push:
    branches:
      - hw06-main
jobs:
  deploy1:
    name: Deploy lambda code for S3 trigger
    # Your repo MUST be in a UConn GitHub Organization that has been configured with RH Runners. 
    # This is a manual task that needs to be completed by the UConn School of Business IT staff.
    # The runs-on value must be "self-hosted" to leverage the runner .
    runs-on: self-hosted

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
          
      # Setp AWS CLI
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # The first parameter can be whatever you want to name your zip file. Really does not matter.
      #   just make sure you use the same file name in the next step below.
      # The second parameter should be the file path of your local lambda code you want to deploy
      - name: Zip python code
        run: zip -j hw06-code.zip ./hw06/lambda_list_buckets.py

      # TODO: Change the --function-name value to match your function name in AWS
      - name: Deploy python code to lambda
        run: aws lambda update-function-code --function-name=hw06-list --zip-file=fileb://hw06-code.zip
        
      # List objects function
      - name: Zip python code
        run: zip -j hw06-code.zip ./hw06/lambda_list_objects.py
      - name: Deploy python code to lambda
        run: aws lambda update-function-code --function-name=hw06-list-objects --zip-file=fileb://hw06-code.zip
      
      # Upload objects function
      - name: Zip python code
        run: zip -j hw06-code.zip ./hw06/lambda_add_object.py
      - name: Deploy python code to lambda
        run: aws lambda update-function-code --function-name=hw06-upload --zip-file=fileb://hw06-code.zip
      
      # Delete objects function
      - name: Zip python code
        run: zip -j hw06-code.zip ./hw06/lambda_delete.py
      - name: Deploy python code to lambda
        run: aws lambda update-function-code --function-name=hw06-delete --zip-file=fileb://hw06-code.zip
      
      # Requirements txt
      - run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f hw06/requirements.txt ]; then pip install -r hw06/requirements.txt; fi
        
      - name: Run all your pytest tests in your code
        run: |
          pytest hw06/test_lambda.py
